// Code generated by mockery v2.14.1. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"
	plog "go.opentelemetry.io/collector/pdata/plog"

	ptrace "go.opentelemetry.io/collector/pdata/ptrace"

	v1 "github.com/f5/otel-arrow-adapter/api/collector/arrow/v1"
)

// ConsumerAPI is an autogenerated mock type for the ConsumerAPI type
type ConsumerAPI struct {
	mock.Mock
}

// LogsFrom provides a mock function with given fields: _a0
func (_m *ConsumerAPI) LogsFrom(_a0 *v1.BatchArrowRecords) ([]plog.Logs, error) {
	ret := _m.Called(_a0)

	var r0 []plog.Logs
	if rf, ok := ret.Get(0).(func(*v1.BatchArrowRecords) []plog.Logs); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]plog.Logs)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(*v1.BatchArrowRecords) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// TracesFrom provides a mock function with given fields: _a0
func (_m *ConsumerAPI) TracesFrom(_a0 *v1.BatchArrowRecords) ([]ptrace.Traces, error) {
	ret := _m.Called(_a0)

	var r0 []ptrace.Traces
	if rf, ok := ret.Get(0).(func(*v1.BatchArrowRecords) []ptrace.Traces); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]ptrace.Traces)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(*v1.BatchArrowRecords) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type mockConstructorTestingTNewConsumerAPI interface {
	mock.TestingT
	Cleanup(func())
}

// NewConsumerAPI creates a new instance of ConsumerAPI. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewConsumerAPI(t mockConstructorTestingTNewConsumerAPI) *ConsumerAPI {
	mock := &ConsumerAPI{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
