// Code generated by mockery v2.14.1. DO NOT EDIT.

package mocks

import (
	v1 "github.com/f5/otel-arrow-adapter/api/collector/arrow/v1"
	mock "github.com/stretchr/testify/mock"
)

// ArrowStreamServiceServer is an autogenerated mock type for the ArrowStreamServiceServer type
type ArrowStreamServiceServer struct {
	mock.Mock
}

// ArrowStream provides a mock function with given fields: _a0
func (_m *ArrowStreamServiceServer) ArrowStream(_a0 v1.ArrowStreamService_ArrowStreamServer) error {
	ret := _m.Called(_a0)

	var r0 error
	if rf, ok := ret.Get(0).(func(v1.ArrowStreamService_ArrowStreamServer) error); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// mustEmbedUnimplementedArrowStreamServiceServer provides a mock function with given fields:
func (_m *ArrowStreamServiceServer) mustEmbedUnimplementedArrowStreamServiceServer() {
	_m.Called()
}

type mockConstructorTestingTNewArrowStreamServiceServer interface {
	mock.TestingT
	Cleanup(func())
}

// NewArrowStreamServiceServer creates a new instance of ArrowStreamServiceServer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewArrowStreamServiceServer(t mockConstructorTestingTNewArrowStreamServiceServer) *ArrowStreamServiceServer {
	mock := &ArrowStreamServiceServer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
