receivers:
  otlp:
    protocols:
      grpc:
  file/traces:
    path: ./recorded_traces.json
    compression: zstd
    format: json
  file/metrics:
    path: ./recorded_metrics.json
    compression: zstd
    format: json

exporters:
  file/traces:
    path: ./replayed_traces.json
    format: json
  file/metrics:
    path: ./replayed_metrics.json
    format: json
  logging:

processors:
  batch:

service:
  pipelines:
    traces:
      receivers: [file/traces]
      processors: [batch]
      exporters: [file/traces, logging]
    metrics:
      receivers: [file/metrics]
      processors: [batch]
      exporters: [file/metrics, logging]